### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by jordanschau** [christophercliff/flatmarket-example#1]
$ ./node_modules/.bin/flatmarket build \
        --component ./lib/index.jsx \
        --stripe-secret-key your_secret_key |
        --dev

I think the above should read:

    $ ./node_modules/.bin/flatmarket build \
    --component ./lib/index.jsx \
    --stripe-secret-key your_secret_key \
    --dev

**Comment by christophercliff** [comment]
Thanks for the tip.
